import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import BannerFg from "../assets/images/banner-fg.png";
import Kfc from "../assets/images/kfc.png";
import DropFresh from "../assets/images/drop-fresh.png";
import Munchies from "../assets/images/munchies.png";
import Service from "../assets/images/service.png";
import Shyft from "../assets/images/shyft.png";
import Stored from "../assets/images/stored.png";
import Medz from "../assets/images/medz.png";
import Segment from "../assets/images/segment-chart.png";
import SMS from "../assets/images/sms.png";
import CrossPlatform from "../assets/images/cross-platform.png";
import Unlock from "../assets/images/unlock.png";
import TrackingSecFg from "../assets/images/engage-fg.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>retayn.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="navbar navbar-light bg-light">
          <div className="container-fluid px-4 py-2">
            <a className={`${styles.purple}`}>retayn.io</a>
            <form className="d-flex">
              <button
                className={`${styles.btn} ${styles.btnNavContact}`}
                type="submit"
              >
                Contact Us
              </button>
            </form>
          </div>
        </nav>

        <div className={styles.banner}>
          <Image
            width="auto"
            height="auto"
            className={styles.bannerFg}
            src={BannerFg}
            alt="Next.js Logo"
            priority
          />
          <div className="h-100 d-flex align-items-center">
            <div className={styles.bannerTextContainer}>
              <p className={styles.bannerHeading}>
                Supercharge your marketing game.{" "}
                <span style={{ color: "#FFA901" }}>
                  Engage & convert like never before
                </span>
              </p>
              <p className={styles.bannerPara}>
                TARGETED MESSAGING . DELIVERY AUTOMATION . ACCELERATED GROWTH
              </p>
              <button
                type="button"
                className={`${styles.btn} ${styles.btnBanner}`}
                onClick={() =>
                  window.open(
                    "https://submit.jotform.com/230713435144044",
                    "_blank"
                  )
                }
              >
                Request a demo
              </button>
            </div>
          </div>
        </div>

        <div className={styles.innovators}>
          <p className={styles.trustHeading}>
            Trusted by global e-commerce innovators
          </p>
          <p className={styles.trustPara}>
            We’ve enabled exponential growth for billion$ companies with
            actionable insights, marketing automation and a simple route to
            build & maintain customer relationships.
          </p>
          <div className={styles.trustImgContainer}>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Medz}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Kfc}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={DropFresh}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Shyft}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Service}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Stored}
                alt="Next.js Logo"
                priority
              />
            </div>
            <div className={styles.trustImg}>
              <Image
                width="auto"
                height="auto"
                className={styles.logo}
                src={Munchies}
                alt="Next.js Logo"
                priority
              />
            </div>
          </div>
        </div>

        <div className={styles.built}>
          <div className={styles.builtContainer}>
            <p className={styles.trustHeading}>
              Built for E-commerce stores on Shopify & Magneto
            </p>
            <p className={styles.trustPara}>
              Purple has every tool you need to drive, measure & optimize
              customer engagement. It is purely designed for e-commerce
              websites, which gives you a unique advantage of having all KPIs &
              metrics aligned with the online shopping industry.
            </p>
          </div>

          <div className={styles.builtSec}>
            <div className="row">
              <div className="col-12 col-lg-5 d-none d-lg-block">
                <div className="d-flex justify-content-center">
                  <Image
                    className={`${styles.builtSecImage} ${styles.userImage}`}
                    src={Segment}
                    alt="Next.js Logo"
                    priority
                  />
                </div>
              </div>
              <div className="col-12 col-lg-7">
                <div className={styles.builtSecHeadingContainer}>
                  <div className={styles.builtSecTopHeading}>
                    <p className={styles.builtSecTopHeadingNumber}>01</p>
                    <p>AUTOMATED USER SEGMENTATION</p>
                  </div>
                </div>
                <div className={styles.builtSecBottom}>
                  <p className={styles.builtSecHeading}>
                    Perfect your audience targeting by grouping your users into
                    real-time segments
                  </p>
                  <ul className={styles.builtSecBullets}>
                    <li>
                      Track users live through real-time purchase behavior.
                      Create segments based on order value, payment method,
                      payment status and discounts.
                    </li>
                    <li>
                      Group users by their locations and conduct A/B tests to
                      improve messaging for better targeting.
                    </li>
                  </ul>
                </div>
              </div>
              <div className="col-12 col-lg-5 d-lg-none">
                <div className="d-flex justify-content-center">
                  <Image
                    className={`${styles.builtSecImage} ${styles.userImage}`}
                    src={Segment}
                    alt="Next.js Logo"
                    priority
                  />
                </div>
              </div>
            </div>
          </div>

          <div className={styles.builtSec}>
            <div className="row">
              <div className="col-12 col-lg-7">
                <div className={styles.builtSecHeadingContainer}>
                  <div className={styles.builtSecTopHeading}>
                    <p className={styles.builtSecTopHeadingNumber}>02</p>
                    <p>SMS & EMAIL MARKETING</p>
                  </div>
                </div>
                <div className={styles.builtSecBottom}>
                  <p className={styles.builtSecHeading}>
                    The personalized, consistent experience your customers need
                    – all through a single platform
                  </p>
                  <ul className={styles.builtSecBullets}>
                    <li>
                      Engage your shoppers wherever they are with email and SMS
                      campaigns.
                    </li>
                    <li>
                      Leverage customizable email and SMS templates to craft a
                      personalized user experience.
                    </li>
                  </ul>
                </div>
              </div>
              <div className="col-12 col-lg-5">
                <Image
                  className={`${styles.builtSecImage} ${styles.marketingImage}`}
                  src={SMS}
                  alt="Next.js Logo"
                  priority
                />
              </div>
            </div>
          </div>

          <div className={styles.builtSec}>
            <div className="row">
              <div className="col-12 col-lg-5 d-none d-lg-block">
                <Image
                  className={`${styles.builtSecImage} ${styles.engagementImage}`}
                  src={CrossPlatform}
                  alt="Next.js Logo"
                  priority
                />
              </div>
              <div className="col-12 col-lg-7">
                <div className={styles.builtSecHeadingContainer}>
                  <div className={styles.builtSecTopHeading}>
                    <p className={styles.builtSecTopHeadingNumber}>03</p>
                    <p>CROSS-CHANNEL ENGAGEMENT</p>
                  </div>
                </div>
                <div className={styles.builtSecBottom}>
                  <p className={styles.builtSecHeading}>
                    Engage and connect with users through highly targeted
                    messaging
                  </p>
                  <ul className={styles.builtSecBullets}>
                    <li>
                      Keep your customers captivated across mobile, web, and
                      other platforms with the right message at the right time.
                    </li>
                    <li>
                      Reach users everywhere through in-app messages, push
                      notifications, SMS, WhatsApp and emails.
                    </li>
                  </ul>
                </div>
              </div>
              <div className="col-12 col-lg-5 d-lg-none">
                <Image
                  className={`${styles.builtSecImage} ${styles.engagementImage}`}
                  src={CrossPlatform}
                  alt="Next.js Logo"
                  priority
                />
              </div>
            </div>
          </div>

          <div className={styles.builtSec}>
            <div className="row">
              <div className="col-12 col-lg-7">
                <div className={styles.builtSecHeadingContainer}>
                  <div className={styles.builtSecTopHeading}>
                    <p className={styles.builtSecTopHeadingNumber}>04</p>
                    <p>INTEGRATIONS</p>
                  </div>
                </div>
                <div className={styles.builtSecBottom}>
                  <p className={styles.builtSecHeading}>
                    Unlock growth by integrating Purple with your existing
                    systems and multiple other tools & APIs
                  </p>
                  <ul className={styles.builtSecBullets}>
                    <li>
                      Integrate chatbots, SMS tools and APIs for any product
                      that helps you boost functionality & productivity.
                    </li>
                    <li>
                      Make Purple yours by having all your favorite apps/tools
                      in sync within our one-stop marketing automation platform.
                    </li>
                  </ul>
                </div>
              </div>
              <div className="col-12 col-lg-5">
                <Image
                  className={`${styles.builtSecImage} ${styles.integrationImage}`}
                  src={Unlock}
                  alt="Next.js Logo"
                  priority
                />
              </div>
            </div>
          </div>

          <div className={styles.expSec}>
            <div className={styles.expSecContainer}>
              <p className={styles.expSecHeading}>
                Experience a smarter e-commerce setup, today!
              </p>
              <p className={styles.expSecPara}>
                Attract, engage and delight your users with Purple. Speak to our
                growth experts to learn how you can embark on a journey to
                retain customers & build long-term partnerships
              </p>
              <button
                type="button"
                className={`${styles.btn} ${styles.expSecBtn}`}
              >
                Talk to an Expert
              </button>
            </div>
          </div>

          <div className={styles.trackingSec}>
            <Image
              width="auto"
              height="auto"
              className={styles.trackingSecFg}
              src={TrackingSecFg}
              alt="Next.js Logo"
              priority
            />
            <div className={styles.trackingSecContainer}>
              <p className={styles.trackingSecHeading}>
                Start tracking and engaging your users in less than 30 minutes!
              </p>
              <div className={styles.trackingSecPara}>
                Purple is built for the Pakistani e-commerce market, keeping
                scale, speed and security in mind. It can be installed in your
                e-commerce store in under 30 minutes.
                <br /> We wanted to. improve how local e-commerce stores on
                Shopify & Magneto track metrics, performance and build trust
                with their users. Purple offers:
                <ul style={{ listStyleType: "none", marginTop: 30 }}>
                  <li>- Affordability</li>
                  <li>- Reliability</li>
                  <li>- Scalability</li>
                  <li>- Accurate Reporting</li>
                  <li>- Data-driven Insights</li>
                  <li>- 24x7 Customer Care </li>
                  <li>- Omnichannel Support</li>
                  <li>- And so much more… </li>
                </ul>
              </div>
              <button
                type="button"
                className={`${styles.btn} ${styles.trackingSecBtn}`}
              >
                Get Started Now
              </button>
            </div>
          </div>

          <div className={styles.contactSec}>
            <div className="row h-100 align-items-center">
              <div className="col-12 col-lg-6">
                <div className={styles.contactSecContainer}>
                  <p className={styles.contactSecHeading}>
                    Ready to scale your e-commerce business with real-time
                    analytics & insights?
                  </p>
                  <div className={styles.contactSecPara}>
                    Let’s go! Fill out the contact form on the right and one of
                    our growth experts will be in touch within 24 hours.
                  </div>
                </div>
              </div>

              <div className="col-12 col-lg-6">
                <div className={styles.contactSecFormContainer}>
                  <form>
                    <div className={styles.contactSecNames}>
                      <div className="form-group w-100">
                        <input
                          type="text"
                          className={`form-control ${styles.contactSecField}`}
                          id="firstName"
                          placeholder="First Name"
                        />
                      </div>
                      <div className="form-group w-100">
                        <input
                          type="text"
                          className={`form-control ${styles.contactSecField}`}
                          id="lastName"
                          placeholder="Last Name"
                        />
                      </div>
                    </div>
                    <div style={{ marginTop: 20 }} className="form-group">
                      <input
                        type="email"
                        className={`form-control ${styles.contactSecField}`}
                        id="exampleFormControlInput1"
                        placeholder="name@example.com"
                      />
                    </div>
                    <div style={{ marginTop: 20 }} className="form-group">
                      <input
                        type="text"
                        className={`form-control ${styles.contactSecField}`}
                        id="exampleFormControlInput1"
                        placeholder="+92 332 2454123"
                      />
                    </div>
                    <div style={{ marginTop: 20 }} className="form-group">
                      <textarea
                        placeholder="How can we help you?"
                        className={`form-control ${styles.contactSecArea}`}
                        id="exampleFormControlTextarea1"
                        rows="3"
                      ></textarea>
                    </div>
                    <div style={{ marginTop: 20 }}>
                      <p className={styles.contactSecAccept}>
                        By sending this form I confirm that I have read and
                        accept VentureDive’s{" "}
                        <span
                          style={{
                            color: "#EE2737",
                            textDecoration: "underline",
                            cursor: "pointer",
                          }}
                        >
                          Privacy Policy
                        </span>
                      </p>
                    </div>
                    <button
                      type="button"
                      className={`${styles.btn} ${styles.contactSecBtn}`}
                    >
                      Submit
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
